server:
  rpc_port: 50301
  http_port: 50302

newrelic:
  appname: mumbai.conetntd.linkit360.com
  license: 4d635427ad90ca786ca2db6aa246ed651730b933

service:
  retry_count: 10
  subscriptions_load_days: 5
  table_prefix: xmp_
  uniq_days: 10
  tables:
  - campaign
  - service
  - content
  - service_content
  - content_sent

  db:
    conn_ttl: -1
    max_conns: 15
    timeout: 30
    name: linkit_mobilink
    user: linkit_mobilink
    pass: A0kZN8pUAs63wePezz
    port: 5432
    host: linkit-mobilink.cb2q7f7mvbwr.ap-south-1.rds.amazonaws.com
    ssl_mode: disable
    table_prefix: xmp_

  db_frankfurt:
    conn_ttl: -1
    max_conns: 15
    timeout: 30
    name: linkit_dev
    user: linkit
    pass: E0kZN8pUAs63wePepf
    port: 5432
    host: linkit.cz3twmoynbq5.eu-central-1.rds.amazonaws.com
    ssl_mode: disable
    table_prefix: xmp_

  notifier:
    queues:
      content_sent: content_sent
    url: amqp://linkit:dg-U_oHhy7-@52.66.23.201:5672
    chan_gap: 10000000