server:
  rpc_port: 50301
  http_port: 50302

service:
  retry_count: 10
  subscriptions_load_days: 5
  uniq_days: 10
  tables:
  - campaign
  - service
  - content
  - service_content
  - content_sent

db:
  conn_ttl: -1
  max_conns: 15
  timeout: 30
  name: linkit_mobilink
  user: linkit_mobilink
  pass: A0kZN8pUAs63wePezz
  port: 5432
  host: ec2-35-154-8-158.ap-south-1.compute.amazonaws.com
  ssl_mode: disable
  table_prefix: xmp_

notifier:
  queues:
    content_sent: content_sent
  rbmq:
    conn:
      user: linkit
      pass: dg-U_oHhy7-
      host: ec2-35-154-8-158.ap-south-1.compute.amazonaws.com
      port: 5672
    chan_capacity: 10000000